DROP TABLE DEPENDENT;
DROP TABLE WORKS_ON;
DROP TABLE PROJECT;
DROP TABLE DEPT_LOCATIONS;
-- use SHOW CREATE TABLE EMPLOYEE to get the foreign key name(we can not use Dno as the name here)
ALTER TABLE EMPLOYEE DROP FOREIGN KEY EMPLOYEE_ibfk_2;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;
