CREATE TABLE PROFESSOR
(
    MID     CHAR(9) PRIMARY KEY,
    NAME    VARCHAR(30),
    TITLE   VARCHAR(20) CHECK (TITLE IN ('ASSISTANT', 'ASSOCIATE', 'FULL', 'ADJUNCT', 'INSTRUCTOR')),
    DNO     INT
);

CREATE TABLE DEPT
(
    DNO     INT PRIMARY KEY,
    DNAME   VARCHAR(30)
);

CREATE TABLE STUDENT
(
    MID     CHAR(9) PRIMARY KEY,
    NAME    VARCHAR(30),
    MAJOR   VARCHAR(30)
);


ALTER TABLE PROFESSOR
    ADD CONSTRAINT DNO_REFERENCE FOREIGN KEY(DNO) REFERENCES DEPT(DNO);

ALTER TABLE PROFESSOR
    DROP CONSTRAINT DNO_REFERENCE;

ALTER TABLE PROFESSOR
    ALTER COLUMN DNO INT NOT NULL 
ALTER TABLE PROFESSOR
	ADD FOREIGN KEY(DNO) REFERENCES DEPT(DNO);

ALTER TABLE PROFESSOR
    ADD SALARY NUMERIC(10,2) DEFAULT 0;

ALTER TABLE PROFESSOR
    ALTER COLUMN NAME VARCHAR(30) NOT NULL;
ALTER TABLE PROFESSOR
	ADD DEFAULT 'UNKNOWN' FOR NAME;
    
INSERT INTO DEPT VALUES(1, 'Computer Science');
INSERT INTO DEPT VALUES(2, 'Chemistry');
INSERT INTO DEPT VALUES(3, 'Physics');
INSERT INTO DEPT VALUES(4, 'Mathematics');

INSERT INTO PROFESSOR(MID, TITLE, DNO) 
    VALUES( '123456789',  'ASSISTANT', 1);

INSERT INTO PROFESSOR 
    VALUES( '987654321', DEFAULT, 'INSTRUCTOR', 2, DEFAULT);
    
INSERT INTO STUDENT
SELECT SSN, CONCAT(CONCAT(LNAME, ', '), FNAME), 'UNKNOWN'
FROM EMPLOYEE;

UPDATE PROFESSOR
    SET NAME='Zhijiang Dong'
    WHERE MID='123456789';
    
UPDATE PROFESSOR
    SET NAME='Fake Name', SALARY=15000.00
    WHERE MID='987654321';

UPDATE PROFESSOR
    SET SALARY = SALARY * 1.2;

UPDATE STUDENT
    SET MAJOR = 'Computer Science'
    WHERE MID LIKE '9%';

UPDATE STUDENT
    SET MAJOR = 'Mathematics'
    WHERE MAJOR='UNKNOWN';



